### ISSUE TITLE
gotta watch errors out when there are no dependencies

### ISSUE THREAD

**Issue by tylerklose** [gotta-dev/gotta-mod#15]
If none of the mods in `mods/` depend on any other mods via `depends_on`, then you will get the following result

```console
tk@tk-macbook-pro email-scheduler (master)*$ gotta watch
WARN: Unresolved or ambigious specs during Gem::Specification.reset:
      ffi (~> 1.0)
      Available/installed versions of this gem:
      - 1.11.1
      - 1.9.25
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Mod 'rubocopify' registered.
Mod 'language_ruby' registered.
Traceback (most recent call last):
	 ...
	 1: from path/to/gotta-dev/gotta-mod/lib/gotta/mod.rb:50:in `now'
path/to/gotta-dev/gotta-mod/lib/gotta/mod/hub.rb:84:in `check_dependencies': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by parruda** [comment]
Good catch!
